*** Settings ***
Documentation				Smoke tests for the PHPTravels site.
Test Template				Perform User Registration
Test Setup					Go to Registration Page
Test Teardown				Close Browser
Resource					${EXECDIR}${/}resources${/}Common.robot


*** Test Cases ***
Failed User Registration
	${EMPTY}				${LAST_NAME}	${MOBILE_NO}	${VALID_EMAIL}		${VALID_PASSWORD}	${VALID_PASSWORD}	${ERROR_MESSAGE}	${MISSING_FNAME_SPIEL}	
	${FIRST_NAME}			${EMPTY}		${MOBILE_NO}	${VALID_EMAIL}		${VALID_PASSWORD}	${VALID_PASSWORD}	${ERROR_MESSAGE}	${MISSING_LNAME_SPIEL}	
	${FIRST_NAME}			${LAST_NAME}	${MOBILE_NO}	${EMPTY}			${VALID_PASSWORD}	${VALID_PASSWORD}	${ERROR_MESSAGE}	${MISSING_EMAIL_SPIEL}	
	${FIRST_NAME}			${LAST_NAME}	${MOBILE_NO}	${VALID_EMAIL}		${EMPTY}			${VALID_PASSWORD}	${ERROR_MESSAGE}	${MISSING_PASSWORD_SPIEL}	
	${FIRST_NAME}			${LAST_NAME}	${MOBILE_NO}	${VALID_EMAIL}		${VALID_PASSWORD}	${EMPTY}	${ERROR_MESSAGE}	${MISSING_PASSWORD_SPIEL}
	${FIRST_NAME}			${LAST_NAME}	${MOBILE_NO}	${INVALID_EMAIL}	${VALID_PASSWORD}	${VALID_PASSWORD}	${ERROR_MESSAGE}	${INVALID_EMAIL_SPIEL}
	${FIRST_NAME}			${LAST_NAME}	${MOBILE_NO}	${VALID_EMAIL}		${SHORT_PASSWORD}	${VALID_PASSWORD}	${ERROR_MESSAGE}	${SHORT_PASSWORD_SPIEL}
	${FIRST_NAME}			${LAST_NAME}	${MOBILE_NO}	${VALID_EMAIL}		${VALID_PASSWORD}	${SHORT_PASSWORD}	${ERROR_MESSAGE}	${NONMATCHING_PASSWORD_SPIEL}


*** Keywords ***
Go to Registration Page
	Open Browser			${HOMEPAGE_URL}	${BROWSER}
	Wait Enabled And Click	${MY_ACCOUNT_MENU}
	Wait Enabled And Click	${SIGN_UP_OPTION}